### ISSUE TITLE
Shared Element throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by TorryDo** [skydoves/Orbital#20]
Library Version: 0.2.4
Kotlin Version: 1.8.0
Compose Compiler Version: 1.4.0
Compose UI version: 1.3.2

Hi.

- I have A TextField under the topbar.
![image](https://user-images.githubusercontent.com/85553681/217992542-30051a60-368b-45a7-b43d-1a6aab9f0abd.png)

- When I click on that TextField, I want to show `SearchComponent()` with that TextField placed on the top of the app, like this:
![image](https://user-images.githubusercontent.com/85553681/217992980-95735b6f-faeb-4d35-a10e-06bf7d31bd0f.png)

but after click, I got this error message instead,

```
java.lang.ArrayIndexOutOfBoundsException: src.length=16 srcPos=4 dst.length=16 dstPos=3 length=-2
    at java.lang.System.arraycopy(Native Method)
    at kotlin.collections.ArraysKt___ArraysJvmKt.copyInto(_ArraysJvm.kt:1247)
    at androidx.compose.runtime.collection.MutableVector.removeAt(MutableVector.kt:795)
    at androidx.compose.ui.node.MutableVectorWithMutationTracking.removeAt(MutableVectorWithMutationTracking.kt:43)
    at androidx.compose.ui.node.LayoutNode.removeAt$ui_release(LayoutNode.kt:287)
    at androidx.compose.ui.node.UiApplier.remove(UiApplier.android.kt:35)
    at androidx.compose.runtime.ComposerImpl$realizeMovement$1.invoke(Composer.kt:3769)
    at androidx.compose.runtime.ComposerImpl$realizeMovement$1.invoke(Composer.kt:3769)
    at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:808)
    ...
```

**This is my code:**

``` kotlin
var isTransformed by rememberSaveable { mutableStateOf(false) }
val sharedSearchBar = rememberContentWithOrbitalScope {
    AppTextField.SearchBar(
        modifier = Modifier
            .height(50.dp)
            .animateSharedElementTransition(
                this,
                TweenSpec(durationMillis = 200),
                TweenSpec(durationMillis = 200)
            ),

        value = textFieldValue,
        placeHolderText = "Search",
        onValueChange = { textFieldValue = it }
    )
}

Scaffold(
    scaffoldState = scaffoldState,
    drawerContent = {...},
    drawerGesturesEnabled = scaffoldState.drawerState.isOpen,
) { paddingValues ->

    Orbital(
        modifier = Modifier
            .fillMaxSize()
            .padding(paddingValues)
            .clickable { isTransformed = !isTransformed }
    ) {

        if (isTransformed) {
            SearchComponent(sharedTextField = { sharedSearchBar() }) {

            }
        } else {

            Column(
                modifier = Modifier
                    .fillMaxSize()
            ) {
                TopBar(
                    onLeftIconClick = {
                        scope.launch {
                            scaffoldState.drawerState.open()
                        }
                    },
                    onRightIconClick = {}
                )

                sharedSearchBar()
            }
        }

    }
}


@Composable
fun SearchComponent(
    sharedTextField: @Composable () -> Unit,
    onBack: () -> Unit
) {

    Column(modifier = Modifier.fillMaxSize()) {
        sharedTextField()
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(Color.Gray)
        ) {
            Button(onClick = { onBack() }) {
                TextComponents.MediumText(text = "Back")
            }
        }
    }
}

```

**Comment by skydoves** [comment]
Hey @TorryDo, this is a very outdated issue since Orbital is 0.3.2 at this moment, so I'm closing this issue. If you still face the same issue with the latest one, please reopen this thread!
